### ISSUE TITLE
Add PIXC tutorials from SWOT ADT Team?

### ISSUE THREAD

**Issue by cassienickles** [SWOT-community/PixCDust#1]
Hi @zawadzl,

Brent Williams from the ADT team sent us some Jupyter Notebooks to add to the PO.DAAC Cookbook and I thought they would be great on the SWOT Community GitHub as well. I see this PixCDust repo now, would this be the best place to add the tutorials? (One is for aggregating pixels into an area and the other is to fix a phase unwrapping error for the PIXC product). Or would the SWOT-Hydrology repo be a better fit?

Notebooks are here for now: 
https://podaac.github.io/tutorials/notebooks/datasets/SWOT_PIXC_Area_localmachine.html
https://podaac.github.io/tutorials/notebooks/datasets/SWOT_PIXC_PhaseUnwrap_localmachine.html

Thanks!

**Comment by zawadzl** [comment]
Hi Cassie, pixcdust is meant as a package for more convenient use of pixel cloud, so I think this would rather go in SWOT-hydrology. I can do that

**Comment by cassienickles** [comment]
Thanks Lionel, great, I put them in the intermediate folder for SWOT hydrology!
